var json_dammutrivningar_15 = {
"type": "FeatureCollection",
"name": "dammutrivningar_15",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "projekt": "Utrivning_Nittkvarndammen", "typ": "Damutrivning", "beskrivning": "Damutrivning där dammen ersattes av konstgjord stentröskel föratt bevara vattennivån uppströms på samma nivå som tidigare. Tröskling skedde uppströms och nedströms dammen för att ta ut lutningen för att säkerställa tröskelns hållbarhet samt gör den lättare att passera. Utrivningen föregigcsav en projekteringgenomförd av Älv-Design AB", "fallhöjd (m)": 1.0, "år": 2023.0, "status": "avslutad", "län": "Dalarna", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB", "intern_id": 0.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Dalarna/Nittälven/Utrivning_Nittkvarn.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Nittkvarn_före.jpg", "efterbild": "images/Nittkvarn_efter.jpg", "länk": "https://storymaps.arcgis.com/stories/4bbb096fd27e4ba282b63a7d9f8243e6", "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Nittkvarn_före' width='400'></b><br><br><b>Efterbild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Nittkvarn_efter' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 14.735075585, 60.045035382999984 ] } },
{ "type": "Feature", "properties": { "projekt": "Utrivning_Gusselby_Kvarndamm", "typ": "Damutrivning", "beskrivning": ".", "fallhöjd (m)": 1.0, "år": 2023.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB", "intern_id": 1.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Gusselby Kvarndamm/Utrivning_Gusselby Kvarndamm 2023.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Gusselby_före.jpg", "efterbild": "images/Gusselby_efter.jpg", "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Gusselby_före' width='400'></b><br><br><b>Efterbild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Gusselby_efter' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 15.219237245554122, 59.648407327671421 ] } }
]
}
