var json_NAP_renden_12 = {
"type": "FeatureCollection",
"name": "NAP_renden_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "projekt": "NAP_ärenden", "typ": "NAP", "beskrivning": "Belganet, Bräkneån", "år": 2022.0, "status": "avslutad", "län": "Blekinge", "beställare": "", "utförare": "SGS Analytics Sweden ABNaturcentrum ABFiskevårdsteknik AB", "intern_id": 0.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/NAP_ärenden.shp", "koordinatsystem": "EPSG:3006", "förebild": "", "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 15.031076777141498, 56.381345433350909 ] } },
{ "type": "Feature", "properties": { "projekt": "NAP_ärenden", "typ": "NAP", "beskrivning": "Bräkneån, Knällsberg", "år": 2022.0, "status": "avslutad", "län": "Kronoberg", "beställare": "", "utförare": "SGS Analytics Sweden AB, Naturcentrum AB, Fiskevårdsteknik AB", "intern_id": 1.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/NAP_ärenden.shp", "koordinatsystem": "EPSG:3006", "förebild": "", "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 14.980493158489203, 56.440489682114979 ] } },
{ "type": "Feature", "properties": { "projekt": "NAP_ärenden", "typ": "NAP", "beskrivning": "Rönneå", "år": 2022.0, "status": "avslutad", "län": "Skåne", "beställare": "", "utförare": "SGS Analytics Sweden AB, Naturcentrum AB, Fiskevårdsteknik AB", "intern_id": 2.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/NAP_ärenden.shp", "koordinatsystem": "EPSG:3006", "förebild": "", "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 13.115662408298144, 56.12347135925075 ] } },
{ "type": "Feature", "properties": { "projekt": "NAP_ärenden", "typ": "NAP", "beskrivning": "Rönneå", "år": 2022.0, "status": "avslutad", "län": "Skåne", "beställare": "", "utförare": "SGS Analytics Sweden AB, Naturcentrum AB, Fiskevårdsteknik AB", "intern_id": 3.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/NAP_ärenden.shp", "koordinatsystem": "EPSG:3006", "förebild": "", "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 13.143080367647777, 56.121584902951383 ] } },
{ "type": "Feature", "properties": { "projekt": "NAP_ärenden", "typ": "NAP", "beskrivning": "Rönneå", "år": 2022.0, "status": "avslutad", "län": "Skåne", "beställare": "", "utförare": "SGS Analytics Sweden AB, Naturcentrum AB, Fiskevårdsteknik AB", "intern_id": 4.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/NAP_ärenden.shp", "koordinatsystem": "EPSG:3006", "förebild": "", "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 13.164999132478858, 56.117429444654206 ] } },
{ "type": "Feature", "properties": { "projekt": "NAP_ärenden", "typ": "NAP", "beskrivning": "Björnamåla", "år": 2022.0, "status": "avslutad", "län": "Blekinge", "beställare": "", "utförare": "SGS Analytics Sweden AB, Naturcentrum AB, Fiskevårdsteknik AB", "intern_id": 5.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/NAP_ärenden.shp", "koordinatsystem": "EPSG:3006", "förebild": "", "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 14.915571336243724, 56.286680825101378 ] } }
]
}
