var json_projektering_dammar_13 = {
"type": "FeatureCollection",
"name": "projektering_dammar_13",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "projekt": "Torphyttedammen", "typ": "Projektering_dammar", "beskrivning": "Projektering av 6 dammar i Örebro län med syfte att undersöka lösningar för att främja longitudinell konnektivitet i berörda vattendrag", "år": 2022.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB, Naturcentrum AB", "intern_id": 0.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Torphyttedammen/Torphyttedammen.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Torphyttedammen_före.jpg", "efterbild": "", "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Torphyttedammen_före' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 15.199009551366073, 59.591253362519637 ] } },
{ "type": "Feature", "properties": { "projekt": "Övre_hyttdammen", "typ": "Projektering_dammar", "beskrivning": "Projektering av 6 dammar i Örebro län med syfte att undersöka lösningar för att främja longitudinell konnektivitet i berörda vattendrag", "år": 2022.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB, Naturcentrum AB", "intern_id": 1.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Färvilsån/Övre Hyttdammen/Övre_hyttdammen.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Övre_hyttdammen_före.JPG", "efterbild": null, "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Övre_hyttdammen_före' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 14.927070902323374, 59.606279664281658 ] } },
{ "type": "Feature", "properties": { "projekt": "Yxedammen", "typ": "Projektering_dammar", "beskrivning": "Projektering av 6 dammar i Örebro län med syfte att undersöka lösningar för att främja longitudinell konnektivitet i berörda vattendrag", "år": 2022.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB, Naturcentrum AB", "intern_id": 2.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Yxedammen/Yxedammen.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Yxedammen_före.JPG", "efterbild": null, "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Yxedammen_före' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 15.150872325412021, 59.526469406866561 ] } },
{ "type": "Feature", "properties": { "projekt": "Storsjödammen", "typ": "Projektering_dammar", "beskrivning": "Projektering av 6 dammar i Örebro län med syfte att undersöka lösningar för att främja longitudinell konnektivitet i berörda vattendrag", "år": 2022.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB, Naturcentrum AB", "intern_id": 3.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Storsjödammen/Storsjödammen.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Storsjödammen_före.JPG", "efterbild": null, "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Storsjödammen_före' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 14.701055708347608, 59.232537388541239 ] } },
{ "type": "Feature", "properties": { "projekt": "Lillsjödammen", "typ": "Projektering_dammar", "beskrivning": "Projektering av 6 dammar i Örebro län med syfte att undersöka lösningar för att främja longitudinell konnektivitet i berörda vattendrag", "år": 2022.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB, Naturcentrum AB", "intern_id": 4.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Lillån/Lillsjödammen.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Lillsjödammen_före.jpg", "efterbild": null, "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Lillsjödammen_före' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 14.730310683150798, 59.230403303279928 ] } },
{ "type": "Feature", "properties": { "projekt": "Håkansbodadammen", "typ": "Projektering_dammar", "beskrivning": "Projektering av 6 dammar i Örebro län med syfte att undersöka lösningar för att främja longitudinell konnektivitet i berörda vattendrag", "år": 2022.0, "status": "avslutad", "län": "Örebro", "beställare": "LST Örebro", "utförare": "SGS Analytics Sweden AB, Älv-Design AB, Naturcentrum AB", "intern_id": 5.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Örebro/Vasslabäcken/Håkansbodasjön/Håkansbodadammen.shp", "koordinatsystem": "EPSG:3006", "förebild": "images/Håkansbodadammen_före.jpg", "efterbild": null, "länk": null, "popup": "<b>Sammanställning SGS Projekt</b><br><br><b>Förebild:</b><br><img src='C:\\Users\\mhx\\Desktop\\GeoJSON_export\\images\\Håkansbodadammen_före' width='400'>" }, "geometry": { "type": "Point", "coordinates": [ 14.914423815092302, 59.68501689560911 ] } }
]
}
