var json_SGS_kontor_14 = {
"type": "FeatureCollection",
"name": "SGS_kontor_14",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "projekt": "SGS_kontor", "typ": "Baskarta", "beskrivning": "Platser där SGS Analytis Sweden AB har sina kontor i Sverige", "år": null, "status": null, "län": null, "beställare": null, "utförare": "SGS Analytics Sweden AB", "intern_id": 0.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/SGS_kontor.shp", "koordinatsystem": "EPSG:3006", "förebild": null, "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 13.478969045099642, 59.388772367760616 ] } },
{ "type": "Feature", "properties": { "projekt": "SGS_kontor", "typ": "Baskarta", "beskrivning": "Platser där SGS Analytis Sweden AB har sina kontor i Sverige", "år": null, "status": null, "län": null, "beställare": null, "utförare": "SGS Analytics Sweden AB", "intern_id": 1.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/SGS_kontor.shp", "koordinatsystem": "EPSG:3006", "förebild": null, "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 15.572876835725976, 58.398276994170985 ] } },
{ "type": "Feature", "properties": { "projekt": "SGS_kontor", "typ": "Baskarta", "beskrivning": "Platser där SGS Analytis Sweden AB har sina kontor i Sverige", "år": null, "status": null, "län": null, "beställare": null, "utförare": "SGS Analytics Sweden AB", "intern_id": 2.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/SGS_kontor.shp", "koordinatsystem": "EPSG:3006", "förebild": null, "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 20.304195800321992, 63.852474326171148 ] } },
{ "type": "Feature", "properties": { "projekt": "SGS_kontor", "typ": "Baskarta", "beskrivning": "Platser där SGS Analytis Sweden AB har sina kontor i Sverige", "år": null, "status": null, "län": null, "beställare": null, "utförare": "SGS Analytics Sweden AB", "intern_id": 3.0, "shp_fil": "C:/Users/mhx/OneDrive - SGS/3.Projekt_Data/Övrigt/Projektsammanställning/SGS_kontor.shp", "koordinatsystem": "EPSG:3006", "förebild": null, "efterbild": null, "länk": null }, "geometry": { "type": "Point", "coordinates": [ 13.059616337665881, 55.607767475614153 ] } }
]
}
